"""
haushalt.py - 15 neue Unterlagen aus einem Privathaushalt.

Ergaenzen die zehn urspruenglichen Testdokumente (Kaufvertrag, Kfz-Police,
Stellplatz, Internet, Strom, Heizung, Waschmaschine, Spende, Drucker,
Reisekosten), die unveraendert im Hauptordner liegen.

Alle Personen, Firmen, Nummern und Betraege sind erfunden. Absichtlich
eingebaut sind STOLPERSTEINE, damit die Suche etwas zu unterscheiden hat:
  - dieselbe Versicherung (Westfalen Direkt) fuer Auto und Hausrat
  - derselbe Anbieter (Nordlicht) fuer Internet und Handy
  - "Heizkosten" in der Nebenkostenabrechnung neben der Heizungswartung
  - dasselbe Auto (BI-MM 1180) in Police, Werkstatt und Haushaltsbuch
  - eine Bedienungsanleitung auf Englisch
  - Dateinamen, die nichts ueber den Inhalt verraten - wie im echten Leben
"""

from .bausteine import Dok

H = "haushalt/"

DOKUMENTE = [
    Dok(H + "Scan_20240131_0001.pdf", "scan", "Entgeltabrechnung",
        stempel=None, inhalt=[
            "Lindner Haustechnik GmbH · Personalabteilung",
            "Eckendorfer Str. 140 · 33609 Bielefeld",
            "",
            "# Abrechnung der Brutto/Netto-Bezüge",
            "Abrechnungsmonat: Januar 2024          Personalnummer: 00417",
            "Herr Max Mustermann, Musterweg 4, 33604 Bielefeld",
            "Steuerklasse I · Kinderfreibetrag 0,0 · Konfession: –",
            "Eintritt: 01.08.2021 · Tätigkeit: Servicetechniker",
            "",
            "## Bezüge",
            "Grundvergütung                                 3.450,00 EUR",
            "Überstundenzuschlag 25 % (6 Std.)                  41,40 EUR",
            "Vermögenswirksame Leistungen AG-Anteil             26,59 EUR",
            "Gesamtbrutto                                   3.517,99 EUR",
            "",
            "## Gesetzliche Abzüge",
            "Lohnsteuer                                       449,58 EUR",
            "Solidaritätszuschlag                               0,00 EUR",
            "Krankenversicherung AN-Anteil 8,15 %             286,72 EUR",
            "Rentenversicherung AN-Anteil 9,3 %               327,17 EUR",
            "Arbeitslosenversicherung AN-Anteil 1,3 %          45,73 EUR",
            "Pflegeversicherung AN-Anteil 2,3 %                80,91 EUR",
            "",
            "Nettobezug                                     2.327,88 EUR",
            "VL-Überweisung Bausparvertrag                     40,00 EUR",
            "Auszahlungsbetrag                              2.287,88 EUR",
            "",
            "Überweisung auf das bekannte Konto zum 31.01.2024.",
            "Resturlaub 2023 übertragen: 4 Tage",
        ]),

    Dok(H + "IMG_5102.pdf", "scan", "Privatliquidation",
        stempel="BEZAHLT|15.05.2024", inhalt=[
            "Zahnarztpraxis Dr. med. dent. Katrin Vogt",
            "Jöllenbecker Str. 212 · 33613 Bielefeld",
            "",
            "Herrn Max Mustermann",
            "Musterweg 4, 33604 Bielefeld",
            "",
            "# Rechnung Nr. 24-0877",
            "Rechnungsdatum: 29.04.2024 · Behandlungszeitraum: 08.04.–22.04.2024",
            "Liquidation nach der Gebührenordnung für Zahnärzte (GOZ)",
            "",
            "Datum      GOZ   Leistung                         Faktor   Betrag",
            "08.04.24   1040  Professionelle Zahnreinigung",
            "                 je Zahn, 28 Zähne                 1,0    104,80",
            "08.04.24   4050  Entfernung harter Beläge          2,3     14,23",
            "22.04.24   2080  Kompositfüllung einflächig,",
            "                 Zahn 36, Adhäsivtechnik           2,3     63,99",
            "22.04.24   0090  Infiltrationsanästhesie           2,3      7,76",
            "",
            "Rechnungsbetrag                                           190,78 EUR",
            "",
            "Bitte überweisen Sie den Betrag innerhalb von 30 Tagen.",
            "Die Rechnung können Sie bei Ihrer Zusatzversicherung einreichen.",
        ]),

    Dok(H + "Abrechnung_HV_2023.pdf", "pdf", "Abrechnung 2023", inhalt=[
        "Hausverwaltung Ostwestfalen e.K. · Detmolder Str. 210 · Bielefeld",
        "",
        "# Betriebskostenabrechnung 2023",
        "Mietobjekt: Musterweg 4, 2. OG links, 68 m²",
        "Mieter: Max Mustermann",
        "Abrechnungszeitraum: 01.01.2023 bis 31.12.2023",
        "",
        "## Umlagefähige Kosten nach Betriebskostenverordnung",
        "Kostenart                 Gesamtkosten   Schlüssel      Ihr Anteil",
        "Grundsteuer                  2.418,00   Wohnfläche         265,98",
        "Wasser und Abwasser          4.960,00   Personen           413,33",
        "Müllabfuhr                   1.872,00   Personen           156,00",
        "Straßenreinigung               388,00   Wohnfläche          42,68",
        "Hausmeister                  3.240,00   Wohnfläche         356,40",
        "Treppenhausreinigung         1.560,00   Wohnfläche         171,60",
        "Gartenpflege                   920,00   Wohnfläche         101,20",
        "Gebäudeversicherung          1.715,00   Wohnfläche         188,65",
        "Allgemeinstrom                 486,00   Wohnfläche          53,46",
        "Heizkosten laut Abrechnung Messdienst (Verbrauch 62 %)   812,40",
        "",
        "Summe Ihrer Kosten                                    2.561,70 EUR",
        "Geleistete Vorauszahlungen 12 x 195,00 EUR            2.340,00 EUR",
        "Nachzahlung                                             221,70 EUR",
        "",
        "Die Nachzahlung ist innerhalb von 30 Tagen nach Zugang fällig.",
        "Die monatliche Vorauszahlung wird ab 01.03.2024 auf 215,00 EUR angepasst.",
        "Belege können nach Terminabsprache in unserem Büro eingesehen werden.",
    ]),

    Dok(H + "Dokument1.docx", "docx", "Brief", inhalt=[
        "Max Mustermann",
        "Musterweg 4",
        "33604 Bielefeld",
        "",
        "FitWerk Sport- und Gesundheitszentrum GmbH",
        "Mitgliederverwaltung",
        "Stapenhorststraße 95",
        "33615 Bielefeld",
        "",
        "Bielefeld, 03.06.2024",
        "",
        "Kündigung meiner Mitgliedschaft – Mitgliedsnummer 20-3318",
        "",
        "Sehr geehrte Damen und Herren,",
        "hiermit kündige ich meinen Mitgliedsvertrag fristgerecht zum nächstmöglichen Zeitpunkt. "
        "Nach meinen Unterlagen endet die Mindestlaufzeit am 30.09.2024.",
        "Bitte ziehen Sie ab diesem Zeitpunkt keine Beiträge mehr von meinem Konto ein und "
        "widerrufen Sie das erteilte SEPA-Lastschriftmandat.",
        "Den Chip für das Drehkreuz und den Spindschlüssel gebe ich beim letzten Training am Empfang ab.",
        "Bitte bestätigen Sie mir den Eingang der Kündigung und das Vertragsende schriftlich.",
        "",
        "Mit freundlichen Grüßen",
        "Max Mustermann",
    ]),

    Dok(H + "Mappe1.xlsx", "xlsx", "Haushaltsbuch", inhalt={
        "Januar": [
            ["Datum", "Kategorie", "Beschreibung", "Betrag (EUR)"],
            ["02.01.2024", "Wohnen", "Miete Stellplatz 14", 45.00],
            ["02.01.2024", "Wohnen", "Abschlag Strom Stadtwerke", 85.00],
            ["03.01.2024", "Lebensmittel", "Wocheneinkauf Supermarkt", 78.43],
            ["05.01.2024", "Auto", "Tanken Super E10, 41 Liter", 72.57],
            ["06.01.2024", "Freizeit", "Beitrag FitWerk", 29.90],
            ["09.01.2024", "Lebensmittel", "Bäcker und Markt", 23.10],
            ["10.01.2024", "Lebensmittel", "Wocheneinkauf Supermarkt", 91.65],
            ["12.01.2024", "Kommunikation", "Internet und Telefon Nordlicht", 46.98],
            ["12.01.2024", "Kommunikation", "Handytarif Mobil M", 17.99],
            ["15.01.2024", "Auto", "Kfz-Versicherung Monatsrate", 34.80],
            ["17.01.2024", "Lebensmittel", "Wocheneinkauf Supermarkt", 84.20],
            ["19.01.2024", "Auto", "Tanken Super E10, 38 Liter", 67.26],
            ["22.01.2024", "Gesundheit", "Apotheke", 12.49],
            ["24.01.2024", "Lebensmittel", "Wocheneinkauf Supermarkt", 69.80],
            ["27.01.2024", "Freizeit", "Kino", 24.00],
            ["31.01.2024", "Lebensmittel", "Getränkemarkt", 18.75],
        ],
        "Übersicht": [
            ["Kategorie", "Januar", "Februar", "März"],
            ["Wohnen", 130.00, 130.00, 130.00],
            ["Lebensmittel", 365.93, 341.20, 388.14],
            ["Auto", 174.63, 102.06, 511.34],
            ["Kommunikation", 64.97, 64.97, 64.97],
            ["Freizeit", 53.90, 29.90, 71.40],
            ["Gesundheit", 12.49, 0.00, 190.78],
            ["Summe", 801.92, 668.13, 1356.63],
        ],
    }),

    Dok(H + "Scan_20240712_0002.pdf", "scan", "", stempel="EINGANG|15. JULI 2024", inhalt=[
        "Finanzamt Bielefeld-Innenstadt",
        "Ravensberger Straße 90 · 33607 Bielefeld",
        "",
        "Herrn Max Mustermann, Musterweg 4, 33604 Bielefeld",
        "Steuernummer 305/5118/4471 · Datum 09.07.2024",
        "",
        "# Bescheid für 2023 über Einkommensteuer, Solidaritätszuschlag",
        "# und Kirchensteuer",
        "",
        "Der Bescheid ist nach § 165 Abs. 1 Satz 2 AO teilweise vorläufig.",
        "",
        "## Festsetzung",
        "                               Einkommensteuer   Solidaritätszuschl.",
        "festgesetzt werden                  5.388,00 EUR            0,00 EUR",
        "ab Steuerabzug vom Lohn            -6.000,00 EUR            0,00 EUR",
        "verbleibende Beträge                 -612,00 EUR            0,00 EUR",
        "",
        "Der Betrag von 612,00 EUR wird auf das angegebene Konto erstattet.",
        "",
        "## Erläuterungen",
        "Bei den Einkünften aus nichtselbständiger Arbeit wurden Werbungskosten",
        "von 1.842,00 EUR berücksichtigt (Entfernungspauschale 220 Tage, Arbeitsmittel,",
        "Fortbildung Netzwerktechnik). Als Sonderausgaben wurden Zuwendungen an",
        "steuerbegünstigte Organisationen in Höhe von 120,00 EUR anerkannt.",
        "Handwerkerleistungen nach § 35a EStG: Ermäßigung 38,00 EUR (Heizungswartung).",
        "",
        "Rechtsbehelfsbelehrung: Der Bescheid kann mit dem Einspruch angefochten",
        "werden. Der Einspruch ist innerhalb eines Monats nach Bekanntgabe einzulegen.",
    ]),

    Dok(H + "Schreiben_0412.pdf", "pdf", "Festsetzungsbescheid", inhalt=[
        "ARD ZDF Deutschlandradio Beitragsservice · 50656 Köln",
        "",
        "Herrn Max Mustermann, Musterweg 4, 33604 Bielefeld",
        "Beitragsnummer 512 884 107",
        "",
        "# Zahlungsaufforderung Rundfunkbeitrag",
        "",
        "Sehr geehrter Herr Mustermann,",
        "für Ihre Wohnung ist der Rundfunkbeitrag zu zahlen. Der Beitrag beträgt monatlich",
        "18,36 EUR und ist nach dem Rundfunkbeitragsstaatsvertrag in der Mitte eines",
        "Dreimonatszeitraums für jeweils drei Monate zu leisten.",
        "",
        "Zeitraum 01.04.2024 bis 30.06.2024 · fällig am 15.05.2024 · 55,08 EUR",
        "",
        "Bequemer geht es mit einem SEPA-Lastschriftmandat: Dann buchen wir den Betrag",
        "automatisch ab und Sie müssen an keinen Zahlungstermin mehr denken.",
        "Wenn Sie Sozialleistungen wie Bürgergeld oder BAföG erhalten, können Sie eine",
        "Befreiung beantragen. Das Formular finden Sie online.",
        "",
        "Mit freundlichen Grüßen",
        "Ihr Beitragsservice",
    ]),

    Dok(H + "VZF_48213.pdf", "pdf", "Vertragszusammenfassung", inhalt=[
        "Nordlicht Telekommunikation GmbH",
        "",
        "# Vertragszusammenfassung Mobilfunk",
        "nach der Durchführungsverordnung (EU) 2019/2243",
        "",
        "Kunde: Max Mustermann · Kundennummer 44-118-3342",
        "Tarif: Nordlicht Mobil M · Rufnummer 0171 0000000",
        "",
        "## Dienste und Geräte",
        "Allnet-Flat Telefonie und SMS in alle deutschen Netze",
        "20 GB Datenvolumen im 5G-Netz, danach 64 kbit/s",
        "EU-Roaming inklusive · eSIM oder SIM-Karte",
        "Smartphone Nordphone 12, 128 GB, Zuzahlung einmalig 49,00 EUR",
        "",
        "## Preise",
        "Monatlicher Grundpreis Monat 1–24            17,99 EUR",
        "Anschlusspreis einmalig                      39,99 EUR",
        "",
        "## Laufzeit, Verlängerung und Kündigung",
        "Mindestvertragslaufzeit 24 Monate ab Aktivierung am 01.03.2023.",
        "Danach monatlich kündbar mit einer Frist von einem Monat.",
        "Rufnummernmitnahme vom bisherigen Anbieter wurde beauftragt.",
    ]),

    Dok(H + "Buchungsbestaetigung.pdf", "pdf", "Reisebestätigung", inhalt=[
        "Sonnenreisen Teuto GmbH · Reisebüro Bielefeld-Mitte",
        "",
        "# Reisebestätigung / Rechnung 2024-11873",
        "Reisende: Max Mustermann, Erika Mustermann",
        "",
        "## Pauschalreise Mallorca",
        "Reisezeitraum: 17.08.2024 bis 31.08.2024 (14 Nächte)",
        "Hotel Cala Serena, Cala d'Or, Doppelzimmer Meerblick, Halbpension",
        "",
        "## Flüge",
        "Hinflug  17.08.2024  Paderborn/Lippstadt (PAD) 06:10 – Palma (PMI) 08:35",
        "Rückflug 31.08.2024  Palma (PMI) 21:50 – Paderborn/Lippstadt (PAD) 00:20",
        "Freigepäck je Person 20 kg, Transfer Flughafen–Hotel inklusive",
        "",
        "Reisepreis 2 Personen                        2.986,00 EUR",
        "Reiserücktrittsversicherung mit Selbstbehalt   118,00 EUR",
        "Gesamtpreis                                  3.104,00 EUR",
        "Anzahlung 20 % bei Buchung                     620,80 EUR",
        "Restzahlung bis 18.07.2024                   2.483,20 EUR",
        "",
        "Bitte denken Sie an gültige Ausweisdokumente. Online-Check-in 48 Stunden",
        "vor Abflug. Sicherungsschein nach § 651r BGB liegt bei.",
    ]),

    Dok(H + "Scan_20240415_0001.pdf", "scan", "", stempel=None, inhalt=[
        "Autohaus Teutoburger Wald GmbH · Meisterwerkstatt",
        "Herforder Straße 301 · 33609 Bielefeld",
        "",
        "# Werkstattrechnung Nr. W-24-2071",
        "Datum: 15.04.2024 · Kunde: Max Mustermann",
        "Fahrzeug: Pkw, amtl. Kennzeichen BI-MM 1180, Erstzulassung 06/2011",
        "Kilometerstand: 162.418",
        "",
        "Pos  Arbeit / Material                                 Betrag",
        "1    Inspektion nach Herstellervorgabe                  189,00",
        "2    Motoröl 5W-30, 4,5 Liter, Ölfilter                  78,40",
        "3    Ölwechsel inkl. Entsorgung Altöl                    29,50",
        "4    Radwechsel Winter auf Sommer, 4 Räder",
        "     auswuchten, Einlagerung Winterräder                 69,00",
        "5    Bremsflüssigkeit erneuert                           54,90",
        "6    Scheibenwischerblätter vorn                         31,80",
        "",
        "Nettobetrag                                             452,60",
        "MwSt. 19 %                                               86,00",
        "Rechnungsbetrag                                         538,60 EUR",
        "",
        "Hinweis: Bremsbeläge hinten bei ca. 3 mm, Austausch in Kürze empfohlen.",
        "Nächste Inspektion bei 177.000 km oder 04/2025.",
    ]),

    Dok(H + "VS-2291-0087.pdf", "pdf", "Versicherungsschein", inhalt=[
        "Westfalen Direkt Versicherung AG",
        "",
        "# Versicherungsschein Hausratversicherung",
        "Versicherungsscheinnummer: HR-2291-0087",
        "Versicherungsnehmer: Max Mustermann, Musterweg 4, 33604 Bielefeld",
        "Beginn: 01.02.2024 · Laufzeit 1 Jahr, verlängert sich jährlich",
        "",
        "## Versicherte Gefahren",
        "Feuer, Leitungswasser, Sturm und Hagel",
        "Einbruchdiebstahl, Raub und Vandalismus nach einem Einbruch",
        "Überspannung durch Blitz",
        "",
        "## Zusatzbausteine",
        "Fahrraddiebstahl bis 1.500 EUR je Fahrrad, auch außerhalb der Wohnung,",
        "sofern das Fahrrad mit einem Schloss gesichert war",
        "Glasbruch für Ceranfeld und Möbelverglasung",
        "",
        "Versicherungssumme 65.000 EUR (Wohnfläche 68 m², Unterversicherungsverzicht)",
        "Selbstbeteiligung je Schadenfall 150 EUR",
        "Jahresbeitrag 112,44 EUR inkl. Versicherungsteuer",
        "",
        "Im Schadenfall melden Sie sich bitte umgehend. Bei Einbruch ist außerdem",
        "unverzüglich Anzeige bei der Polizei zu erstatten und eine Stehlgutliste einzureichen.",
    ]),

    Dok(H + "Zeugnis_final.docx", "docx", "Zeugnis", inhalt=[
        "Bürotechnik Nordwest GmbH",
        "Ravensberger Str. 88 · 33607 Bielefeld",
        "",
        "# Arbeitszeugnis",
        "Herr Max Mustermann, geboren am 14.03.1998, war vom 01.08.2018 bis zum 31.07.2021 "
        "in unserem Unternehmen als Servicetechniker für Bürosysteme beschäftigt.",
        "Die Bürotechnik Nordwest GmbH betreut mit 40 Mitarbeitern Kunden in Ostwestfalen bei "
        "Kauf, Aufstellung und Wartung von Multifunktionssystemen und Netzwerken.",
        "Zu seinen Aufgaben gehörten die Installation und Einrichtung von Druck- und "
        "Kopiersystemen beim Kunden, die Anbindung an Windows-Netzwerke, die Störungsbeseitigung "
        "vor Ort sowie die Einweisung der Anwender.",
        "Herr Mustermann verfügt über ein umfassendes und fundiertes Fachwissen, das er stets "
        "sicher und zielgerichtet einsetzte. Er arbeitete jederzeit selbstständig, sorgfältig "
        "und äußerst zuverlässig. Seine Arbeitsergebnisse waren stets von sehr guter Qualität.",
        "Wir waren mit seinen Leistungen stets in vollem Umfang zufrieden.",
        "Sein Verhalten gegenüber Vorgesetzten, Kollegen und Kunden war stets vorbildlich.",
        "Herr Mustermann verlässt uns auf eigenen Wunsch. Wir bedauern dies sehr, danken ihm "
        "für die stets sehr gute Zusammenarbeit und wünschen ihm für seine berufliche und "
        "private Zukunft alles Gute und weiterhin viel Erfolg.",
        "",
        "Bielefeld, 31.07.2021",
        "Andreas Meyer, Geschäftsführer",
    ]),

    Dok(H + "manual_EN.pdf", "pdf", "BaristaPro 3000 Quick Guide", inhalt=[
        "# BaristaPro 3000 – Quick Reference Guide",
        "Fully automatic espresso and coffee machine · Model BP-3000",
        "",
        "## Descaling the machine",
        "Limescale builds up over time and affects the taste of your coffee.",
        "When the display shows DESCALE, the machine must be descaled.",
        "1. Empty the drip tray and the coffee grounds container.",
        "2. Remove the water filter from the water tank, if installed.",
        "3. Pour 0.5 l of liquid descaler into the tank and fill up to the MAX mark.",
        "4. Place a container of at least 1 l under the coffee spout and the steam wand.",
        "5. Press and hold the CARE button for 3 seconds. The program takes about 25 minutes.",
        "6. Rinse the water tank and fill it with fresh water when prompted.",
        "",
        "## Water hardness",
        "Set the water hardness in the menu under SETTINGS > WATER. Use the test strip",
        "supplied. With the water filter installed, descaling is required less often.",
        "",
        "## Error messages",
        "E1  Water tank empty or not inserted correctly",
        "E2  Grounds container full",
        "E4  Brewing unit blocked – remove and rinse the brewing unit under running water",
        "E7  Temperature sensor fault – switch off and contact customer service",
        "",
        "Warranty: 24 months from date of purchase. Keep your receipt.",
    ]),

    Dok(H + "Präsentation1.pptx", "pptx", "JHV 2024", inhalt=[
        ("Jahreshauptversammlung 2024", ["TuS Ostwestfalen 1912 e.V.",
                                        "Vereinsheim, 15. März 2024, 19:00 Uhr"]),
        ("Tagesordnung", ["Bericht des Vorstands", "Kassenbericht und Bericht der Kassenprüfer",
                          "Entlastung des Vorstands", "Beitragsordnung ab 2025",
                          "Projekt Kunstrasenplatz", "Wahlen", "Verschiedenes"]),
        ("Kassenbericht 2023", ["Einnahmen aus Beiträgen: 48.600 EUR",
                                "Zuschüsse Stadtsportbund: 6.200 EUR",
                                "Ausgaben Platzpflege und Energie: 21.900 EUR",
                                "Rücklage Kunstrasen: 35.000 EUR"]),
        ("Beitragsordnung ab 01.01.2025", ["Erwachsene: 14 EUR statt 12 EUR monatlich",
                                           "Kinder und Jugendliche: 8 EUR statt 7 EUR",
                                           "Familienbeitrag: 30 EUR monatlich",
                                           "Aufnahmegebühr entfällt"]),
        ("Projekt Kunstrasenplatz", ["Baukosten ca. 780.000 EUR",
                                     "Förderung Land NRW bis zu 50 %",
                                     "Baubeginn geplant Sommer 2025",
                                     "Arbeitsgruppe sucht noch Helfer"]),
        ("Wahlen", ["2. Vorsitzende/r", "Kassenwart/in", "Zwei Kassenprüfer/innen"]),
    ]),

    Dok(H + "notizen.txt", "txt", "Notizen", inhalt=[
        "Bad oben – Renovierung",
        "",
        "Wanne raus, bodengleiche Dusche 90x120 mit Glaswand",
        "Fliesen: Feinsteinzeug 60x60 anthrazit matt, ca. 24 m² Wand + 6 m² Boden",
        "Angebot Fliesenleger Brockmann: 4.850 EUR inkl. Abdichtung, ohne Material",
        "Angebot Sanitär Sundermann: Unterputz-Armatur + Rinne 2.300 EUR",
        "Waschtisch 80 cm mit Unterschrank – im Baumarkt ansehen",
        "Handtuchheizkörper elektrisch? Steckdose fehlt, Elektriker fragen",
        "Budget gesamt max. 12.000 EUR",
        "Vermieter wegen Genehmigung anschreiben!!",
        "Zeitraum: nach dem Urlaub, ab September",
    ]),
]
